- name: Docker API dependencies on the remote host
  hosts: all
  roles:
    - role: roles/docker-pip3

- name: Træfik
  hosts:
    - itsidevfsd0005
  gather_facts: yes   ## Just for the FQDN
  roles:
    - role: roles/docker-traefik
  vars_files:
    - vars/global-vars.yml
  vars:
    traefik_root_location: /srv/traefik
    # traefik_external_https_port is defined in vars/global-vars.yml
    traefik_certificate_selfsigned_subject: >-
      /CN={{ ansible_facts["fqdn"] }}

- name: Foreman server
  hosts:
    - itsidevfsd0005
  gather_facts: yes   # Need FQDN too
  roles:
    - role: roles/foreman-idevfsd
  vars_files:
    - vars/global-vars.yml

- name: Foreman remastered discovery image
  hosts:
    - itsidevfsd0005
  gather_facts: no
  roles:
    - role: roles/foreman-discovery-remaster
  vars_files:
    - vars/global-vars.yml
