- name: Docker API dependencies on the remote host
  hosts: all
  roles:
    - role: roles/docker-pip3

- name: Træfik
  hosts:
    - itsidevfsd0005
  gather_facts: yes   ## Just for the FQDN
  roles:
    - role: roles/docker-traefik
  vars:
    traefik_root_location: /srv/traefik
    traefik_external_https_port: 7443
    traefik_certificate_selfsigned_subject: >-
      /CN={{ ansible_facts["fqdn"] }}

- name: Foreman server
  hosts:
    - itsidevfsd0005
  gather_facts: no   # We don't use them
  roles:
    - role: roles/foreman-idevfsd
