- name: Docker API dependencies on the remote host
  hosts: all
  roles:
    - role: roles/docker-pip3

- name: Install Docker
  hosts: dojo1  # TODO: make a group, srlsly
  gather_facts: yes
  tasks:
  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg
  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
  - name: Install list of packages
    apt:
      name: ['apt-transport-https','ca-certificates','curl','software-properties-common','docker-ce']
      state: present
      update_cache: yes

- name: "Dedicated Docker network for Foreman"
  gather_facts: no
  hosts:
    - dojo1
  tasks:
    - docker_network:
        name: "{{ foreman_docker_network_name }}"
  vars_files:
    - vars/global-vars.yml

- name: Træfik
  hosts:
    - dojo1
  gather_facts: yes   ## Just for the FQDN
  roles:
    - role: roles/docker-traefik
  vars_files:
    - vars/global-vars.yml
  vars:
    traefik_root_location: /srv/traefik
    # traefik_external_https_port is defined in vars/global-vars.yml
    traefik_certificate_selfsigned_subject: >-
      /CN={{ ansible_facts["fqdn"] }}
    traefik_networks:
      - name: "{{ foreman_docker_network_name }}"
    traefik_http_on_https_port: true

- name: Foreman server
  hosts:
    - dojo1
  gather_facts: yes   # Need FQDN too
  roles:
    - role: roles/foreman-idevfsd
  vars_files:
    - vars/global-vars.yml

- name: Foreman remastered discovery image
  hosts:
    - dojo1
  gather_facts: no
  roles:
    - role: roles/foreman-discovery-remaster
  vars_files:
    - vars/global-vars.yml
