## Single-file inventory (no distinction between test and production)
all:
  hosts:
    dojo1:
      inventory_environment: prod
      ansible_host: 10.92.104.103
      ansible_user: root
      ansible_python_interpreter: python3


