## Single-file inventory (no distinction between test and production)
all:
  hosts:
    itsidevfsd0005:
      inventory_environment: test
      ansible_host: 10.92.104.103
      ansible_user: root
      ansible_python_interpreter: python3


