- name: "Ensure that {{ discovery_source_dir }} is present"
  changed_when: false
  shell:
    cmd: |
      if test -d "{{ discovery_source_dir }}"; then exit 0; fi

      cat >&2 <<MESSAGE
      Please ensure that {{ discovery_source_dir }} is mounted, e.g. with

      mount -t cifs -o username=YOURGASPARLOGIN //nassvmmix01.epfl.ch/si_vsissp_iso_priv_repo_p01_app/ITServices/its_idevfsd {{ discovery_remastered_image | dirname }}

      MESSAGE

      exit 1

- name: "Download {{ discovery_source_url | basename }}"
  get_url:
    url: "{{ discovery_source_url }}"
    dest: "{{ discovery_source_dir }}"
    force: no   # Don't attempt to re-download if file is already there
    checksum: "md5:{{ discovery_source_md5sum }}"

- name: "Run discovery-remaster"
  shell:
    creates: "{{ discovery_remastered_image }}"
    cmd: |
      discovery-remaster "{{ discovery_source_image }}" \
         '{% for k in discovery_remaster_tags.keys() -%}
          {#- -#}{{ k }}={{ discovery_remaster_tags[k] }} {# -#}
          {%- endfor %}' \
         "{{ discovery_remastered_image }}"
