- name: "Discovery remastering dependencies"
  include_tasks:
    file: discovery-remaster-deps.yml
    apply:
      tags:
        - discovery
        - discovery.deps
  tags:
    - discovery
    - discovery.deps

- name: "discovery-remaster script"
  get_url:
    url: https://raw.githubusercontent.com/theforeman/foreman-discovery-image/master/aux/remaster/discovery-remaster
    dest: /usr/local/sbin/discovery-remaster
    mode: "0755"
  tags:
    - discovery
    - discovery.script

- name: "Run discovery-remaster"
  include_tasks:
    file: discovery-remaster-do.yml
    apply:
      tags:
        - discovery
        - discovery.remaster
  tags:
    - discovery
    - discovery.remaster
  
