foreman_topdir: /srv/foreman

foreman_postgres_image: postgres:12
foreman_postgres_socket_dir: "{{ foreman_topdir }}/run/postgres"
foreman_postgres_storage_dir: "{{ foreman_topdir }}/data/postgres"
foreman_postgres_root_password_file: "{{ foreman_topdir }}/postgres-root-password"
foreman_postgres_initdb_sql_script: "{{ foreman_topdir }}/data/initdb.sql"

foreman_version: 2.3.2
foreman_frontend_base_image: "quay.io/foreman/foreman:{{ foreman_version }}"
foreman_frontend_build_dir: "{{ foreman_topdir }}/build/frontend"
foreman_frontend_image: "epflidevfsd/foreman:{{ foreman_version }}"
foreman_frontend_container_name: "foreman_{{ inventory_environment }}"
foreman_frontend_config_dir: "{{ foreman_topdir }}/config"
foreman_frontend_mounts:
  - type: bind
    source: "{{ foreman_postgres_socket_dir }}"
    target: /run/postgres
  - type: bind
    source: "{{ foreman_frontend_config_dir }}/database.yml"
    target: /home/foreman/config/database.yml
  - type: bind
    source: "{{ foreman_frontend_config_dir }}/settings.yaml"
    target: /home/foreman/config/settings.yaml

foreman_smartproxy_build_dir: "{{ foreman_topdir }}/build/smartproxy"
foreman_smartproxy_image: "epflidevfsd/foreman-smartproxy:{{ foreman_version }}"
foreman_smartproxy_container_name: "smartproxy_{{ inventory_environment }}"

foreman_docker_rails_interpreter:
  - docker
  - exec
  - "-i"
  - "{{ foreman_frontend_container_name }}"
  - bundle
  - exec
  - rails
  - console

foreman_keybase_credentials_file: /keybase/team/epfl_idevfsd/foreman/credentials.yml
_foreman_keybase_credentials: >-
  {{ lookup("file", foreman_keybase_credentials_file) | from_yaml }}
foreman_admin_user: "{{ _foreman_keybase_credentials.foreman_web_ui.login }}"
foreman_admin_password: "{{ _foreman_keybase_credentials.foreman_web_ui.password }}"

foreman_api_environment:
  FOREMAN_SERVER_URL: "{{ foreman_frontend_url }}"
  FOREMAN_USERNAME: "{{ foreman_admin_user }}"
  FOREMAN_PASSWORD: "{{ foreman_admin_password }}"
  FOREMAN_VALIDATE_CERTS: no

foreman_main_organization_name: IDEV-FSD
foreman_main_location_name: XaaS Prod

foreman_default_install:
  architecture: "x86_64"
  operatingsystem: "Ubuntu 20.04"
  medium: "Ubuntu mirror"
  ptable: "Preseed default LVM"
