foreman_topdir: /srv/foreman

foreman_postgres_image: postgres:12
foreman_postgres_socket_dir: "{{ foreman_topdir }}/run/postgres"
foreman_postgres_storage_dir: "{{ foreman_topdir }}/data/postgres"
foreman_postgres_root_password_file: "{{ foreman_topdir }}/postgres-root-password"
foreman_postgres_initdb_sql_script: "{{ foreman_topdir }}/data/initdb.sql"

foreman_frontend_image: quay.io/foreman/foreman:2.3.2
foreman_frontend_container_name: "foreman_{{ inventory_environment }}"
foreman_frontend_config_dir: "{{ foreman_topdir }}/config"
foreman_frontend_mounts:
  - type: bind
    source: "{{ foreman_postgres_socket_dir }}"
    target: /run/postgres
  - type: bind
    source: "{{ foreman_frontend_config_dir }}/database.yml"
    target: /home/foreman/config/database.yml
  - type: bind
    source: "{{ foreman_frontend_config_dir }}/settings.yaml"
    target: /home/foreman/config/settings.yaml
