- name: "{{ hostgroup.domain }} domain"
  environment: "{{ foreman_api_environment }}"
  theforeman.foreman.domain:
    name: "{{ hostgroup.domain }}"
    organizations: "{{ foreman_main_organization_name }}"
    locations: "{{ foreman_main_location_name }}"

- name: "/24 subnet(s) for {{ hostgroup_name }}"
  when: >-
    hostgroup.subnet | regex_search("/24$")
  environment: "{{ foreman_api_environment }}"
  theforeman.foreman.subnet:
    name: "{{ subnet }}.0/24"
    network: "{{ subnet }}.0"
    mask: "255.255.255.0"
    gateway: "{{ subnet }}.1"
    domains: "{{ hostgroup.domain }}"
    dns_primary: 128.178.15.227
    dns_secondary: 128.178.15.228
    boot_mode: "Static"
  with_items: >-
    {{ (hostgroup.hosts | valuesets)["ip"] | subnets_24 }}
  loop_control:
    loop_var: subnet

- name: "/16 subnet(s) for {{ hostgroup_name }}"
  when: >-
    hostgroup.subnet | regex_search("/16$")
  environment: "{{ foreman_api_environment }}"
  theforeman.foreman.subnet:
    name: "{{ subnet }}.0.0/16"
    network: "{{ subnet }}.0.0"
    mask: "255.255.0.0"
    gateway: "{{ subnet }}.0.1"
    domains: "{{ hostgroup.domain }}"
    dns_primary: 128.178.15.227
    dns_secondary: 128.178.15.228
    boot_mode: "Static"
  with_items: >-
    {{ (hostgroup.hosts | valuesets)["ip"] | subnets_16 }}
  loop_control:
    loop_var: subnet

- name: "{{ hostgroup_name }} host group"
  environment: "{{ foreman_api_environment }}"
  theforeman.foreman.hostgroup:
    name: "{{ hostgroup_name }}"
    organization:    "{{ foreman_hostgroup_params.organization }}"
    locations:       "{{ foreman_hostgroup_params.locations }}"
    domain:          "{{ foreman_hostgroup_params.domain }}"
    subnet:          "{{ foreman_hostgroup_params.subnet }}"
    architecture:    "{{ foreman_hostgroup_params.architecture }}"
    operatingsystem: "{{ foreman_hostgroup_params.operatingsystem }}"
    medium:          "{{ foreman_hostgroup_params.medium }}"
    ptable:          "{{ foreman_hostgroup_params.ptable }}"
    parameters: "{{ fixed_parameters + managed_parameters | from_yaml }}"
  vars:
    ssh_keys: >-
      {{ hostgroup.root_ssh_keys }}
    fixed_parameters:
      - name: host_registration_remote_execution
        parameter_type: boolean
        value: >-
          {{ hostgroup.root_ssh_keys | selectattr("from", "eq", "foreman") | length > 0 }}
      - name: epfl_root_authorized_keys
        parameter_type: string
        value: >-
          {{ lookup("template", "ssh_keys") }}
    managed_parameters: |
      {% for var in foreman_hostgroup_ansible_vars %}
      - name: {{ var.name }}
        parameter_type: {{ var.type }}
        value: {{ hostgroup.parameters[var.name] | default(var.default_value) }}
      {% endfor %}

- name: "{{ hostgroup_name }} root password (not useable over the network)"
  environment: "{{ foreman_api_environment }}"
  theforeman.foreman.hostgroup:
    name: "{{ hostgroup_name }}"
    root_pass: >-
      {{ hostgroup.root_pass
         | default(hostgroup_name) }}
  ## "Will result in the entity always being updated, as the current
  ## password cannot be retrieved". Sigh
  changed_when: false

- name: "Hosts of {{ hostgroup_name }}"
  with_items: "{{ hostgroup.hosts }}"
  environment: "{{ foreman_api_environment }}"
  theforeman.foreman.host:
    name: >-
      {{ item.fqdn | default(item.name + "." + hostgroup.domain) }}
    hostgroup: "{{ hostgroup_name }}"
    mac: >-
      {{ item.mac | default(None) }}
    ip: >-
      {{ item.ip  | default(None) }}
    # These parameters are inherited from the host group at creation
    # time (see `initialize` method in app/models/host/managed.rb line
    # 78). Unfortunately this means we have to enforce them again
    # here, lest when we change an already existing host group with
    # existing hosts, the change won't trickle down to the latter:
    architecture:    "{{ foreman_hostgroup_params.architecture }}"
    operatingsystem: "{{ foreman_hostgroup_params.operatingsystem }}"
    medium:          "{{ foreman_hostgroup_params.medium }}"
    ptable:          "{{ foreman_hostgroup_params.ptable }}"
    subnet:          "{{ foreman_hostgroup_params.subnet }}"
    organization: >-
      {{ hostgroup.organization
         | default(foreman_main_organization_name) }}
    location: >-
      {{ hostgroup.location
         | default(foreman_main_location_name) }}
    parameters: "{{ item.parameters | as_foreman_parameters }}"
