- name: "{{ hostgroup.domain }} domain"
  environment: "{{ foreman_api_environment }}"
  theforeman.foreman.domain:
    name: "{{ hostgroup.domain }}"
    organizations: "{{ foreman_main_organization_name }}"
    locations: "{{ foreman_main_location_name }}"

- name: "/24 subnets"
  environment: "{{ foreman_api_environment }}"
  theforeman.foreman.subnet:
    name: "{{ subnet }}.0/24"
    network: "{{ subnet }}.0"
    mask: "255.255.255.0"
    gateway: "{{ subnet }}.1"
    domains: "{{ hostgroup.domain }}"
    dns_primary: 128.178.15.227
    dns_secondary: 128.178.15.228
    boot_mode: "Static"
  with_items: >-
    {{ (hostgroup.hosts | valuesets)["ip"] | subnets_24 }}
  loop_control:
    loop_var: subnet

- name: "{{ hostgroup_name }} host group"
  environment: "{{ foreman_api_environment }}"
  theforeman.foreman.hostgroup:
    name: "{{ hostgroup_name }}"
    organization: >-
      {{ hostgroup.organization
         | default(foreman_main_organization_name) }}
    locations: >-
      {{ hostgroup.location
         | default(foreman_main_location_name) }}
    domain: "{{ hostgroup.domain }}"
    subnet: "{{ hostgroup.subnet }}"
    architecture: >-
      {{ hostgroup.architecture
         | default(foreman_default_install.architecture) }}
    operatingsystem: >-
      {{ hostgroup.operatingsystem
         | default(foreman_default_install.operatingsystem) }}
    medium: >-
      {{ hostgroup.medium
         | default(foreman_default_install.medium) }}
    ptable: >-
      {{ hostgroup.ptable
         | default(foreman_default_install.ptable) }}
    parameters: "{{ fixed_parameters + managed_parameters | from_yaml }}"
  vars:
    ssh_keys: >-
      {{ hostgroup.root_ssh_keys }}
    fixed_parameters:
      - name: host_registration_remote_execution
        parameter_type: boolean
        value: >-
          {{ hostgroup.root_ssh_keys | selectattr("from", "eq", "foreman") | length > 0 }}
      - name: epfl_root_authorized_keys
        parameter_type: string
        value: >-
          {{ lookup("template", "ssh_keys") }}
    managed_parameters: |
      {% for var in foreman_hostgroup_ansible_vars %}
      - name: {{ var.name }}
        parameter_type: {{ var.type }}
        value: {{ hostgroup.parameters[var.name] | default(var.default_value) }}
      {% endfor %}

- name: "{{ hostgroup_name }} root password (not useable over the network)"
  environment: "{{ foreman_api_environment }}"
  theforeman.foreman.hostgroup:
    name: "{{ hostgroup_name }}"
    root_pass: >-
      {{ hostgroup.root_pass
         | default(hostgroup_name) }}
  ## "Will result in the entity always being updated, as the current
  ## password cannot be retrieved". Sigh
  changed_when: false

- name: "Hosts of {{ hostgroup_name }}"
  with_items: "{{ hostgroup.hosts }}"
  environment: "{{ foreman_api_environment }}"
  theforeman.foreman.host:
    name: >-
      {{ item.fqdn | default(item.name + "." + hostgroup.domain) }}
    hostgroup: "{{ hostgroup_name }}"
    mac: >-
      {{ item.mac | default(None) }}
    ip: >-
      {{ item.ip  | default(None) }}
    organization: >-
      {{ hostgroup.organization
         | default(foreman_main_organization_name) }}
    location: >-
      {{ hostgroup.location
         | default(foreman_main_location_name) }}
    operatingsystem: Ubuntu 20.04
    architecture: x86_64
    parameters: "{{ item.parameters | as_foreman_parameters }}"
