- name: "Administrator password"
  rails_script:
    interpreter: "{{ foreman_docker_rails_interpreter }}"
    postcondition: |
      User::try_to_login "{{ foreman_admin_user }}", "{{ foreman_admin_password }}"
    action: |
      admin = User.unscoped.find_by_login "{{ foreman_admin_user }}"
      admin.upgrade_password "{{ foreman_admin_password }}"
      admin.save
    recheck: yes

- name: "Ubuntu 20.04"
  environment: "{{ foreman_api_environment }}"
  theforeman.foreman.operatingsystem:
    name: Ubuntu
    release_name: focal
    family: Debian
    major: "20"
    minor: "04"
    password_hash: SHA256
    ## “x86_64” architecture, “Ubuntu mirror” media and “Preseed
    ## default LVM” partition table template are all pre-seededin
    ## Foreman
    architectures:
      - x86_64
    media:
      - "Ubuntu mirror"
    ptables:
      - "Preseed default LVM"
  tags:
    - foreman.config.os
