- include_vars:
    name: foreman_inventory
    file: "../../../managed-inventory.yml"
  tags: always

- name: Install the YAML Python API
  pip:
    executable: pip3
    name:
      - PyYAML
    state: latest

- name: "Ubuntu 20.04"
  environment: "{{ foreman_api_environment }}"
  theforeman.foreman.operatingsystem:
    name: Ubuntu
    release_name: focal
    family: Debian
    major: "20"
    minor: "04"
    password_hash: SHA256
    ## Literal values below are all pre-seeded during Foreman install
    architectures:
      - x86_64
    media:
      - "Ubuntu mirror"
    ptables:
      - "Preseed default LVM"
    provisioning_templates:
      ## See explanations below
      - "Discovery Debian kexec"
      - "Preseed default iPXE"
      - "Preseed default"
      - "Preseed default finish"
      - "Preseed default user data"
      - "Linux registration default"
  tags:
    - foreman.config.os

- name: "Ubuntu 20.04 default templates"
  environment: "{{ foreman_api_environment }}"
  theforeman.foreman.os_default_template: >-
    {{ item.update({"operatingsystem": "Ubuntu 20.04" }) | default(item, true) }}
  with_items:
      ## This says how the PXE-less discovery process
      ## (https://theforeman.org/plugins/foreman_discovery/15.0/index.html#5.3PXE-lessdiscovery)
      ## boots into install mode:
    - template_kind: "kexec"
      provisioning_template: "Discovery Debian kexec"
      ## This governs the main install process
    - template_kind: "provision"
      provisioning_template: "Preseed default"
    - template_kind: "finish"
      provisioning_template: "Preseed default finish"
    - template_kind: "registration"
      provisioning_template: "Linux registration default"
    - template_kind: "iPXE"
      provisioning_template: "Preseed default iPXE"
  tags: foreman.config.os.templates

- name: "Ubuntu 20.04 mirror"
  environment: "{{ foreman_api_environment }}"
  theforeman.foreman.installation_medium:
    name: "Ubuntu mirror"
    path: "http://install.iccluster.epfl.ch/mirrors/ubuntu/ubuntu"
    organizations:
      - "{{ foreman_main_organization_name }}"
    locations:
      - "{{ foreman_main_location_name }}"

- name: "Preseed default finish custom snippet"
  environment: "{{ foreman_api_environment }}"
  theforeman.foreman.provisioning_template:
    # As the name implies, `Preseed default finish` calls out to this one
    name: "Preseed default finish custom snippet"
    kind: snippet
    template: >-
      {{ lookup("template", "preseed-finish.sh") }}

- name: "Per-hostgroup finish snippets"
  environment: "{{ foreman_api_environment }}"
  theforeman.foreman.provisioning_template:
    name: "{{ hostgroup_name }} finish snippet"
    kind: snippet
    template: |
      {{ hostgroup["finish_snippet"] }}
  vars:
    hostgroup: "{{ foreman_inventory[hostgroup_name] }}"
  when: >-
    "finish_snippet" in hostgroup
  with_items: "{{ foreman_inventory.keys() }}"
  loop_control:
    loop_var: hostgroup_name
