- name: "Foreman PostgreSQL database"
  include_tasks:
    file: foreman-postgres.yml
    apply:
      tags:
        - foreman
        - foreman.postgres
  tags:
    - foreman
    - foreman.postgres

- name: "Foreman smart proxy"
  include_tasks:
    file: foreman-smartproxy.yml
    apply:
      tags:
        - foreman
        - foreman.smartproxy
  tags:
    - foreman
    - foreman.smartproxy
    - foreman.smartproxy.image

- name: "Foreman front-end server"
  include_tasks:
    file: foreman-frontend.yml
    apply:
      tags:
        - foreman
        - foreman.frontend
  tags:
    - foreman
    - foreman.frontend
    - foreman.frontend.image
    - foreman.frontend.dockerfile

- name: "Foreman configuration"
  include_tasks:
    file: foreman-config.yml
    apply:
      tags:
        - foreman
        - foreman.config
  tags:
    - foreman
    - foreman.config
    - foreman.config.os
    - foreman.config.kubespray
    - foreman.config.kubespray.jobtemplate

- include_vars:
    name: foreman_inventory
    file: "../../../managed-inventory.yml"
  tags:
    - foreman
    - foreman.inventory

- name: "Foreman host groups"
  include_tasks:
    file: _hostgroup.yml
    apply:
      tags:
        - foreman
        - foreman.inventory
  vars:
    hostgroup: "{{ foreman_inventory[hostgroup_name] }}"
  with_items: "{{ foreman_inventory.keys() }}"
  loop_control:
    loop_var: hostgroup_name
  tags:
    - foreman
    - foreman.inventory
