- name: "Administrator password"
  rails_script:
    interpreter: "{{ foreman_docker_rails_interpreter }}"
    postcondition: |
      User::try_to_login "{{ foreman_admin_user }}", "{{ foreman_admin_password }}"
    action: |
      admin = User.unscoped.find_by_login "{{ foreman_admin_user }}"
      admin.upgrade_password "{{ foreman_admin_password }}"
      admin.save
    recheck: yes

- name: "Connect to smart proxy"
  environment: "{{ foreman_api_environment }}"
  theforeman.foreman.smart_proxy:
    name: "smart proxy in Docker"
    ## Use a FQDN because some API endpoints (e.g. the one when
    ## the smart proxy is done with some remote ssh execution)
    ## perform DNS-based authentication:
    url: "http://{{ foreman_smartproxy_container_name }}.{{ foreman_docker_network_name }}:8000"
    organizations:
      - "{{ foreman_main_organization_name }}"
    locations:
      - "{{ foreman_main_location_name }}"
    state: present

- name: "unattended_url"
  environment: "{{ foreman_api_environment }}"
  theforeman.foreman.setting:
    name: "unattended_url"
    value: >-
      {{ foreman_frontend_url | replace("https://", "http://") }}

- name: "Ubuntu 20.04"
  environment: "{{ foreman_api_environment }}"
  theforeman.foreman.operatingsystem:
    name: Ubuntu
    release_name: focal
    family: Debian
    major: "20"
    minor: "04"
    password_hash: SHA256
    ## Literal values below are all pre-seeded during Foreman install
    architectures:
      - x86_64
    media:
      - "Ubuntu mirror"
    ptables:
      - "Preseed default LVM"
    provisioning_templates:
      ## See explanations below
      - "Discovery Debian kexec"
      - "Preseed default"
      - "Preseed default finish"
      - "Preseed default user data"
  tags:
    - foreman.config.os

- name: "Ubuntu 20.04 default templates"
  environment: "{{ foreman_api_environment }}"
  theforeman.foreman.os_default_template: "{{ item }}"
  with_items:
    - operatingsystem: "Ubuntu 20.04"
      ## This says how the PXE-less discovery process
      ## (https://theforeman.org/plugins/foreman_discovery/15.0/index.html#5.3PXE-lessdiscovery)
      ## boots into install mode:
      template_kind: "kexec"
      provisioning_template: "Discovery Debian kexec"
      ## This governs the main install process
    - operatingsystem: "Ubuntu 20.04"
      template_kind: "provision"
      ## TODO: this template insists on setting up a root password.
      provisioning_template: "Preseed default"
    - operatingsystem: "Ubuntu 20.04"
      template_kind: "finish"
      provisioning_template: "Preseed default finish"
      ## This ensures that Foreman obtains ssh access to the installed node
    - operatingsystem: "Ubuntu 20.04"
      template_kind: "user_data"
      provisioning_template: "Preseed default user data"

- name: "Ubuntu 20.04 mirror"
  environment: "{{ foreman_api_environment }}"
  theforeman.foreman.installation_medium:
    name: "Ubuntu mirror"
    path: "http://install.iccluster.epfl.ch/mirrors/ubuntu/ubuntu"
    organizations:
      - "{{ foreman_main_organization_name }}"
    locations:
      - "{{ foreman_main_location_name }}"
