- name: "Foreman PostgreSQL database"
  include_tasks:
    file: foreman-postgres.yml
    apply:
      tags:
        - foreman
        - foreman.postgres
  tags:
    - foreman
    - foreman.postgres

- name: "Foreman front-end server"
  include_tasks:
    file: foreman-frontend.yml
    apply:
      tags:
        - foreman
        - foreman.frontend
  tags:
    - foreman
    - foreman.frontend
    - foreman.frontend.image
    - foreman.frontend.dockerfile

- name: "Foreman configuration"
  include_tasks:
    file: foreman-config.yml
    apply:
      tags:
        - foreman
        - foreman.config
  tags:
    - foreman
    - foreman.config
    - foreman.config.os
    - foreman.config.hostgroup
    - foreman.config.domain
    - foreman.config.subnets
