{# Variables and bogus default values for a nonexistent `kubespray`
 # role, that Ansible will import.
 #
 # The actual management of these values is done under -t foreman.config.kubespray
 #}

# Per-node variables:
etcd_member_name: ""
kubespray_is_kube_master: false
kubespray_is_kube_node: false
kubespray_is_calico_rr: false

# Per-hostgroup variables:
{% for var in foreman_hostgroup_ansible_vars %}
{% if var.type == "string" %}
{{ var.name }}: ""
{% elif var.type == "boolean" %}
{{ var.name }}: false
{% elif var.type == "integer" %}
{{ var.name }}: 0
{% endif %}
{% endfor %}
