{# This file undergoes no less than three steps of macro-expansion,
 # which are (in order):
 #
 #  Where              What                        Braces
 #
 #  Your workstation   Ansible `template` task     triple-mustache
 #  Foreman            JobTemplate erb processing  pointy-angle percent
 #  Smart proxy        ansible-runner              Single-mustache percent and
 #                                                 double-mustache (i.e. “regular” Ansible)
 #
 # (For the overly curious, this here comment is eliminated in the first step.)
 #}
<%-# Fall back to regular “Ansible - Default” template, unless the host group
   # is set to apply exactly the “kubespray” role.
   # Note: this is far from fool-proof, since foreman-ansible running ansible-runner
   # ignores all rendered job templates except the first one. Do not attempt to mix
   # and match Kubespray and non-Kubespray host groups in a single Ansible playbook run!
  %>
<% if (['kubespray'] != @host.hostgroup.all_ansible_roles.map { |role| role.name })  %>
<%= render_template("Ansible Roles - Ansible Default") %>
<% else %>

# The cwd is something like /tmp/d20210307-18-np2moy/project
#
# The directory layout under /tmp/d20210307-18-np2moy looks like
#
# data            # The inventory from Foreman, in JSON
# inventory/
#   hosts         # A weird executable script generated by foreman_ansible_core's
#                 # ForemanAnsibleCore::Runner::AnsibleRunner, that just `cat`s
#                 # the `data` JSON file
# project/
#   playbook.yml  # This here template ends up there
- name: Kubespray prepare steps
  hosts: localhost
  tasks:
    - name: Read inventory
      shell: cat ../data
      register: _inventory

    - name: Parse inventory
      set_fact:
        _foreman_inventory: "{{ _inventory.stdout | from_json }}"

    - name: Augment inventory with groups
      copy:
        dest: ../inventory/hosts
        mode: "0644"
        content: |
          all:
            vars:
              {# For some reason, and as noted in the comments of
               # https://stackoverflow.com/a/44734246/435004,
               # ansible_ssh_private_key_file won't work as a regular
               # per-host variable: -#}
              ansible_ssh_private_key_file: /root/.ssh/id_rsa_foreman_proxy
            children:
              k8s-cluster:
                hosts:
          {{{ "{%" }}} for host in hostvars %}
                  {{ host }}:
                    vars:
                      {{ _foreman_inventory["_meta"]["hostvars"][host] | to_yaml |
                         indent(width=12) }}
          {{{ "{%" }}} endfor %}
              # https://github.com/kubernetes-sigs/kubespray/blob/master/docs/ansible.md#inventory
              kube-node:
                hosts: {{
                  kube_nodes      | trim | default('{}', true) | from_yaml | to_json }}
              kube-master:
                hosts: {{
                  kube_masters    | trim | default('{}', true) | from_yaml | to_json }}
              etcd:
                hosts: {{
                  etcd_nodes      | trim | default('{}', true) | from_yaml | to_json }}
              calico-rr:
                hosts: {{
                  calico_rr_nodes | trim | default('{}', true) | from_yaml | to_json }}
      vars:
        hostvars: >-
          {{ _foreman_inventory["_meta"]["hostvars"] }}
        kube_nodes: |
          {{{ "{%" }}} for host in hostvars %}
          {{{ "{%" }}} if hostvars[host].kubespray_is_kube_node | default(False) %}
          {{ host }}: {}
          {{{ "{%" }}} endif %}
          {{{ "{%" }}} endfor %}
        kube_masters: |
          {{{ "{%" }}} for host in hostvars %}
          {{{ "{%" }}} if hostvars[host].kubespray_is_kube_master | default(False) %}
          {{ host }}: {}
          {{{ "{%" }}} endif %}
          {{{ "{%" }}} endfor %}
        etcd_nodes: |
          {{{ "{%" }}} for host in hostvars %}
          {{{ "{%" }}} if ( (hostvars[host].etcd_member_name is defined) and
                            (hostvars[host].etcd_member_name | length > 0) ) %}
          {{ host }}: {}
          {{{ "{%" }}} endif %}
          {{{ "{%" }}} endfor %}
        calico_rr_nodes: |
          {{{ "{%" }}} for host in hostvars %}
          {{{ "{%" }}} if hostvars[host].is_calico_rr | default(False) %}
          {{ host }}: {}
          {{{ "{%" }}} endif %}
          {{{ "{%" }}} endfor %}

    - name: Re-read inventory
      meta: refresh_inventory

################################################################################
# The remainder of this playbook is an adapted copy of /usr/share/kubespray/cluster.yml

{{{ kubespray_main_playbook
    | regex_replace("^---$", "", multiline=True)
    | regex_replace("import_([^:]*):\s+(\S.*)", "import_\\1: /usr/share/kubespray/\\2") }}}
<% end %>
