## There is no default for the following variables, and the
## playbook must define these:
## - traefik_root_location

traefik_docker_image: "traefik:v2.4"
traefik_container_name: traefik
traefik_networks: []
traefik_static_config_file_path: "{{ traefik_root_location }}/conf/traefik.yml"
traefik_dynamic_config_dir: "{{ traefik_root_location }}/conf/dynamic"
traefik_container_restart_policy: "always"
## If true, the websecure entryPoint will *not* be fitted with a
## default http → tls section. This means that all containers
## (actually, all routers) are free to request TLS support
## using e.g. a `traefik.http.routers.foo.tls: "true"` label,
## or opt not to. This gives one the ability to mix HTTP and
## HTTP/S traffic on the same port (at the cost of additional
## scrutinity required to enforce security).
traefik_http_on_https_port: false

## Feature flags
traefik_use_docker_labels: true
traefik_produce_access_logs: true
traefik_debug: false

traefik_log_max_size: 50m
traefik_log_rotate_keep_number: 3

## If you pre-populate these files, the role won't override them.
traefik_ssl_certs_location: "{{ traefik_root_location }}/certs"
traefik_ssl_keys_location: "{{ traefik_root_location }}/certs/private"
traefik_ssl_key_path: "{{ traefik_ssl_keys_location }}/key.pem"
traefik_ssl_cert_path: "{{ traefik_ssl_certs_location }}/cert.pem"

## traefik_external_http_port is not defined by default. If it is,
## then it 302's everything to traefik_https_port.
traefik_external_https_port: 443

traefik_rsa_key_size: 2048
traefik_certificate_selfsigned_subject: "/CN=traefik"
traefik_certificate_selfsigned: true
traefik_certificate_selfsigned_validity_days: 3650
